name: Deploy

on:
  push:
    branches:
      - main
      - release
      - prod
      - preprod
      - dev

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: SSH into EC2 and deploy
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}/softwareIntegration
            git pull origin ${{ github.ref }}
            npm install
            npm restart 
          EOF

      - name: Clean up SSH key
        run: rm private_key.pem
