name: Android CI

on:
  pull_request:
    branches: [ "main", "dev", "prod", "preprod", "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run lint tests
      run: bash .github/workflows/workflow_scripts/run_linting
    - name: Run build
      run: bash .github/workflows/workflow_scripts/run_build
    - name: Run tests
      run: bash .github/workflows/workflow_scripts/run_tests