name: PR-branch-review

on:
  pull_request:
    branches: [ "main", "dev", "prod", "preprod", "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Make executable
      run: sudo chmod +x ./.github/workflows/workflow_scripts/*
    - name: Run lint test
      run: ./.github/workflows/workflow_scripts/run_linting
    - name: Run build
      run: bash .github/workflows/workflow_scripts/run_build
    - name: Run tests
      run: bash .github/workflows/workflow_scripts/run_tests
