name: PR-branch-review

on:
  pull_request:
    branches: ['main', 'dev', 'prod', 'preprod', 'release']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Make executable
        run: sudo chmod +x ./workflow_scripts/*
      - name: Run lint test
        run: ./workflow_scripts/run_linting
      - name: Run build
        run: ./workflow_scripts/run_build
      - name: Run tests
        run: ./workflow_scripts/run_tests
